export interface MxImp {
    fkId :number,
    fkDate :string,
    fkTime :string,
    price :number,
    trend :number,
    mountain :number,
    valley :number,
    fkSign :string,
    fkInterest :number,
    fkPrevOrderLocation :number,
    fsSign :string,
    fsInterest :number,
    fsPrevOrderLocation :number,
    refkSign :string,
    refkInterest :number,
    refkPrevOrderLocation :number,
    mxSign :string,
    mxInterest :number,
    mxPrevOrderLocation :number,
}
